# Challenge Part 3: Create direction layer to draw the route to four cities

In [7]:
import pandas as pd 
import requests 
import gmaps

from config import g_key

In [8]:
gmaps.__version__

'0.9.0'

In [9]:
gmaps.configure(api_key=g_key)

In [10]:
vacation_df = pd.read_csv("city_data.csv")
vacation_df.head()

,Unnamed: 0,Unnamed: 0.1,city,Lat,Lng,Max Temp,Current Description,Rain (inches),Snow (inches),Humidity,Cloudiness,Wind Speed,Country
0,0,0,port elizabeth,-33.92,25.57,48.20,light rain,0.48,0,76,89,10.29,ZA
1,1,1,faanui,-16.48,-151.75,79.66,light rain,0.40,0,77,0,5.70,PF
2,2,2,ugra,54.78,34.33,54.64,moderate rain,1.29,0,97,100,16.53,RU
3,3,3,jucuapa,13.52,-88.38,91.40,light rain,0.75,0,63,64,1.92,SV
4,4,4,port alfred,-33.59,26.89,51.31,light rain,0.29,0,73,76,15.17,ZA

In [11]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Hotel Name</dt><dd>{Hotel Name} at {Max Temp}</dd>
"""

hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]
locations = vacation_df[["Lat", "Lng"]]

KeyError: 'Hotel Name'

In [12]:
marker_layer = gmaps.marker_layer[locations, info_box_content=hotel_info]
fig = gmaps.figure()
fig.add_layer(marker_layer)

fig

SyntaxError: invalid syntax (<ipython-input-12-a1642ba8b19d>, line 1)

In [13]:
vacation_start = vacation_df.loc[vacation_df["city"] == "port elizabeth"]
vacation_end = vacation_df.loc[vacation_df["city"] == "faanui"]
vacation_stop1 = vacation_df.loc[vacation_df["city"] == "ugra"]
vacation_stop2 = vacation_df.loc[vacation_df["city"] == "jucuapa"]

In [14]:
start = vacation_start["Lat"].values[0], vacation_stop1["Lng"].values[0]
end = vacation_end["Lat"].values[0], vacation_stop1["Lng"].values[0]
stop1 = vacation_stop1["Lat"].values[0], vacation_stop1["Lng"].values[0]
stop2 = vacation_stop2["Lat"].values[0], vacation_stop2["Lng"].values[0]
print(start)
print(end)
print(stop1)
print(stop2)

(-33.92, 34.33)
(-16.48, 34.33)
(54.78, 34.33)
(13.52, -88.38)

In [15]:
fig = gmaps.figure()
vacation_itineray = gmaps.directions_layer(
    start,end,waypoints=[stop1,stop2],
    travel_mode="DRIVING"
)
fig.add_layer(vacation_itinerary)
fig

NameError: name 'vacation_itinerary' is not defined

In [16]:
intinerary_df = pd.concat([vacation_start, vacation_end, vacation_stop1, vacation_stop2])
intinerary_df

,Unnamed: 0,Unnamed: 0.1,city,Lat,Lng,Max Temp,Current Description,Rain (inches),Snow (inches),Humidity,Cloudiness,Wind Speed,Country
0,0,0,port elizabeth,-33.92,25.57,48.20,light rain,0.48,0,76,89,10.29,ZA
1,1,1,faanui,-16.48,-151.75,79.66,light rain,0.40,0,77,0,5.70,PF
2,2,2,ugra,54.78,34.33,54.64,moderate rain,1.29,0,97,100,16.53,RU
3,3,3,jucuapa,13.52,-88.38,91.40,light rain,0.75,0,63,64,1.92,SV

In [17]:
intinerary_df.reset_index(drop=True)

,Unnamed: 0,Unnamed: 0.1,city,Lat,Lng,Max Temp,Current Description,Rain (inches),Snow (inches),Humidity,Cloudiness,Wind Speed,Country
0,0,0,port elizabeth,-33.92,25.57,48.20,light rain,0.48,0,76,89,10.29,ZA
1,1,1,faanui,-16.48,-151.75,79.66,light rain,0.40,0,77,0,5.70,PF
2,2,2,ugra,54.78,34.33,54.64,moderate rain,1.29,0,97,100,16.53,RU
3,3,3,jucuapa,13.52,-88.38,91.40,light rain,0.75,0,63,64,1.92,SV